---

# STACKING & UNSTACKING DATAFRAMES

---

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
churn = pd.read_csv('Resources/churn-bigml-20.csv')
churn.head()

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,LA,117,408,No,No,0,184.5,97,31.37,351.6,80,29.89,215.8,90,9.71,8.7,4,2.35,1,False
1,IN,65,415,No,No,0,129.1,137,21.95,228.5,83,19.42,208.8,111,9.40,12.7,6,3.43,4,True
2,NY,161,415,No,No,0,332.9,67,56.59,317.8,97,27.01,160.6,128,7.23,5.4,9,1.46,4,True
3,SC,111,415,No,No,0,110.4,103,18.77,137.3,102,11.67,189.6,105,8.53,7.7,6,2.08,2,False
4,HI,49,510,No,No,0,119.3,117,20.28,215.1,109,18.28,178.7,90,8.04,11.1,1,3.00,1,False

<br><br>

---

## 1. Stacking DataFrames

---

<BR>

---

### Example No. 1 Setting a MultiIndex

In [3]:
# Method NO. 1
draft1 = churn.set_index(['State', 'Area code'])
draft1.head()

,,Account length,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
State,Area code,,,,,,,,,,,,,,,,,,
LA,408,117,No,No,0,184.5,97,31.37,351.6,80,29.89,215.8,90,9.71,8.7,4,2.35,1,False
IN,415,65,No,No,0,129.1,137,21.95,228.5,83,19.42,208.8,111,9.40,12.7,6,3.43,4,True
NY,415,161,No,No,0,332.9,67,56.59,317.8,97,27.01,160.6,128,7.23,5.4,9,1.46,4,True
SC,415,111,No,No,0,110.4,103,18.77,137.3,102,11.67,189.6,105,8.53,7.7,6,2.08,2,False
HI,510,49,No,No,0,119.3,117,20.28,215.1,109,18.28,178.7,90,8.04,11.1,1,3.00,1,False

In [4]:
# Method NO. 2 - Using MultiIndex and "from_arrays"
# Step 1: Create a 2D Numpy array of 2 columns...
new_array = np.array([np.arange(1000,1667), np.arange(3000, 3667)])
new_array

array([[1000, 1001, 1002, ..., 1664, 1665, 1666],
       [3000, 3001, 3002, ..., 3664, 3665, 3666]])

In [5]:
# Method NO. 2 - Using MultiIndex and "from_arrays
# Step 2: Create the MultiIndex...
draft2 = churn.copy()
draft2.index = pd.MultiIndex.from_arrays(new_array, names=['One_k', 'Three_k'])
draft2.head()

,,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
One_k,Three_k,,,,,,,,,,,,,,,,,,,,
1000,3000,LA,117,408,No,No,0,184.5,97,31.37,351.6,80,29.89,215.8,90,9.71,8.7,4,2.35,1,False
1001,3001,IN,65,415,No,No,0,129.1,137,21.95,228.5,83,19.42,208.8,111,9.40,12.7,6,3.43,4,True
1002,3002,NY,161,415,No,No,0,332.9,67,56.59,317.8,97,27.01,160.6,128,7.23,5.4,9,1.46,4,True
1003,3003,SC,111,415,No,No,0,110.4,103,18.77,137.3,102,11.67,189.6,105,8.53,7.7,6,2.08,2,False
1004,3004,HI,49,510,No,No,0,119.3,117,20.28,215.1,109,18.28,178.7,90,8.04,11.1,1,3.00,1,False

In [6]:
# Method NO.3 - Create MultiIndex and MultiColumns
# Step 1: Create the MultiColumns
idx = pd.MultiIndex.from_arrays(new_array, names=['One_k', 'Three_k'])

new_array2 = np.array([np.arange(10, 30), ['A','B','C','D','E','F','G','H','I','J',
                                       'K','L','M','N','O','P','Q','R','S','T']])
cols = pd.MultiIndex.from_arrays(new_array2, names=['numbers', 'letters'])

In [7]:
# Method NO.3 - Create MultiIndex and MultiColumns
# Step 2: Create the DataFrame with MultiIndex and MultiColumns
draft3 = pd.DataFrame(churn)
draft3.index = idx
draft3.columns = cols
draft3

,numbers,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29
,letters,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T
One_k,Three_k,,,,,,,,,,,,,,,,,,,,
1000,3000,LA,117,408,No,No,0,184.5,97,31.37,351.6,80,29.89,215.8,90,9.71,8.7,4,2.35,1,False
1001,3001,IN,65,415,No,No,0,129.1,137,21.95,228.5,83,19.42,208.8,111,9.40,12.7,6,3.43,4,True
1002,3002,NY,161,415,No,No,0,332.9,67,56.59,317.8,97,27.01,160.6,128,7.23,5.4,9,1.46,4,True
1003,3003,SC,111,415,No,No,0,110.4,103,18.77,137.3,102,11.67,189.6,105,8.53,7.7,6,2.08,2,False
1004,3004,HI,49,510,No,No,0,119.3,117,20.28,215.1,109,18.28,178.7,90,8.04,11.1,1,3.00,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1662,3662,WI,114,415,No,Yes,26,137.1,88,23.31,155.7,125,13.23,247.6,94,11.14,11.5,7,3.11,2,False
1663,3663,AL,106,408,No,Yes,29,83.6,131,14.21,203.9,131,17.33,229.5,73,10.33,8.1,3,2.19,1,False
1664,3664,VT,60,415,No,No,0,193.9,118,32.96,85.0,110,7.23,210.1,134,9.45,13.2,8,3.56,3,False
1665,3665,WV,159,415,No,No,0,169.8,114,28.87,197.7,105,16.80,193.7,82,8.72,11.6,4,3.13,1,False
1666,3666,CT,184,510,Yes,No,0,213.8,105,36.35,159.6,84,13.57,139.2,137,6.26,5.0,10,1.35,2,False

<br><br>

---

### Example No. 2 Setting a MultiIndex

---

In [66]:
draft1 = churn.copy()
draft1.head()

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,LA,117,408,No,No,0,184.5,97,31.37,351.6,80,29.89,215.8,90,9.71,8.7,4,2.35,1,False
1,IN,65,415,No,No,0,129.1,137,21.95,228.5,83,19.42,208.8,111,9.40,12.7,6,3.43,4,True
2,NY,161,415,No,No,0,332.9,67,56.59,317.8,97,27.01,160.6,128,7.23,5.4,9,1.46,4,True
3,SC,111,415,No,No,0,110.4,103,18.77,137.3,102,11.67,189.6,105,8.53,7.7,6,2.08,2,False
4,HI,49,510,No,No,0,119.3,117,20.28,215.1,109,18.28,178.7,90,8.04,11.1,1,3.00,1,False

In [67]:
# Configurating the stacked columns 
origin_cols = list(draft1.columns)
new_array3 = np.array([np.arange(10, 30), ['A','B','C','D','E','F','G','H','I','J',
                                       'K','L','M','N','O','P','Q','R','S','T'], origin_cols])
cols = pd.MultiIndex.from_arrays(new_array3, names=['numbers', 'letters', 'original_names'])
draft1.columns = cols
draft1

numbers,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29
letters,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T
original_names,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,LA,117,408,No,No,0,184.5,97,31.37,351.6,80,29.89,215.8,90,9.71,8.7,4,2.35,1,False
1,IN,65,415,No,No,0,129.1,137,21.95,228.5,83,19.42,208.8,111,9.40,12.7,6,3.43,4,True
2,NY,161,415,No,No,0,332.9,67,56.59,317.8,97,27.01,160.6,128,7.23,5.4,9,1.46,4,True
3,SC,111,415,No,No,0,110.4,103,18.77,137.3,102,11.67,189.6,105,8.53,7.7,6,2.08,2,False
4,HI,49,510,No,No,0,119.3,117,20.28,215.1,109,18.28,178.7,90,8.04,11.1,1,3.00,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
662,WI,114,415,No,Yes,26,137.1,88,23.31,155.7,125,13.23,247.6,94,11.14,11.5,7,3.11,2,False
663,AL,106,408,No,Yes,29,83.6,131,14.21,203.9,131,17.33,229.5,73,10.33,8.1,3,2.19,1,False
664,VT,60,415,No,No,0,193.9,118,32.96,85.0,110,7.23,210.1,134,9.45,13.2,8,3.56,3,False
665,WV,159,415,No,No,0,169.8,114,28.87,197.7,105,16.80,193.7,82,8.72,11.6,4,3.13,1,False
666,CT,184,510,Yes,No,0,213.8,105,36.35,159.6,84,13.57,139.2,137,6.26,5.0,10,1.35,2,False

<br><br>

---

### The `.stack()` Method

---

<br>

In [78]:
# Let's take a look at the original dataframe
churn.head(3)

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,LA,117,408,No,No,0,184.5,97,31.37,351.6,80,29.89,215.8,90,9.71,8.7,4,2.35,1,False
1,IN,65,415,No,No,0,129.1,137,21.95,228.5,83,19.42,208.8,111,9.40,12.7,6,3.43,4,True
2,NY,161,415,No,No,0,332.9,67,56.59,317.8,97,27.01,160.6,128,7.23,5.4,9,1.46,4,True

In [80]:
df_stacked = pd.melt(frame=churn, id_vars=['State', 'Account length', 'Area code', 'International plan', 'Voice mail plan', 'Churn'],
                     value_vars=['Total day minutes', 'Total day calls', 'Total day charge', 'Customer service calls'],
                     var_name='feature', value_name='actual_value')
df_stacked.set_index(['State', 'Area code'])

,,Account length,International plan,Voice mail plan,Churn,feature,actual_value
State,Area code,,,,,,
LA,408,117,No,No,False,Total day minutes,184.5
IN,415,65,No,No,True,Total day minutes,129.1
NY,415,161,No,No,True,Total day minutes,332.9
SC,415,111,No,No,False,Total day minutes,110.4
HI,510,49,No,No,False,Total day minutes,119.3
...,...,...,...,...,...,...,...
WI,415,114,No,Yes,False,Customer service calls,2.0
AL,408,106,No,Yes,False,Customer service calls,1.0
VT,415,60,No,No,False,Customer service calls,3.0
WV,415,159,No,No,False,Customer service calls,1.0
CT,510,184,Yes,No,False,Customer service calls,2.0

In [94]:
a = df_stacked.sort_values(by='State')
a

,State,Account length,Area code,International plan,Voice mail plan,Churn,feature,actual_value
1681,AK,96,408,No,Yes,False,Total day charge,25.50
896,AK,115,415,No,No,False,Total day calls,105.00
347,AK,96,408,No,Yes,False,Total day minutes,150.00
2348,AK,96,408,No,Yes,False,Customer service calls,1.00
940,AK,76,415,No,Yes,False,Total day calls,107.00
...,...,...,...,...,...,...,...,...
788,WY,111,415,No,No,False,Total day calls,55.00
1810,WY,146,415,No,Yes,False,Total day charge,30.72
1558,WY,53,415,No,Yes,False,Total day charge,4.40
1127,WY,127,510,Yes,No,False,Total day calls,99.00
1376,WY,215,510,No,No,False,Total day charge,14.21

In [96]:
a.unstack('feature')

KeyError: 'Requested level (feature) does not match index name (None)'

<br><br>

---

## 2.Unstacking DataFrames

---

In [65]:
df_stacked.unstack()

numbers                    10                                         \
letters                     A
original_names Account length Area code Churn Customer service calls
0                         NaN       NaN   NaN                    NaN
1                         NaN       NaN   NaN                    NaN
2                         NaN       NaN   NaN                    NaN
3                         NaN       NaN   NaN                    NaN
4                         NaN       NaN   NaN                    NaN
..                        ...       ...   ...                    ...
662                       NaN       NaN   NaN                    NaN
663                       NaN       NaN   NaN                    NaN
664                       NaN       NaN   NaN                    NaN
665                       NaN       NaN   NaN                    NaN
666                       NaN       NaN   NaN                    NaN

numbers                                                                        \
letters
original_names International plan Number vmail messages State Total day calls
0                             NaN                   NaN    LA             NaN
1                             NaN                   NaN    IN             NaN
2                             NaN                   NaN    NY             NaN
3                             NaN                   NaN    SC             NaN
4                             NaN                   NaN    HI             NaN
..                            ...                   ...   ...             ...
662                           NaN                   NaN    WI             NaN
663                           NaN                   NaN    AL             NaN
664                           NaN                   NaN    VT             NaN
665                           NaN                   NaN    WV             NaN
666                           NaN                   NaN    CT             NaN

numbers                                            ...              29  \
letters                                            ...               T
original_names Total day charge Total day minutes  ... Total eve calls
0                           NaN               NaN  ...             NaN
1                           NaN               NaN  ...             NaN
2                           NaN               NaN  ...             NaN
3                           NaN               NaN  ...             NaN
4                           NaN               NaN  ...             NaN
..                          ...               ...  ...             ...
662                         NaN               NaN  ...             NaN
663                         NaN               NaN  ...             NaN
664                         NaN               NaN  ...             NaN
665                         NaN               NaN  ...             NaN
666                         NaN               NaN  ...             NaN

numbers                                                             \
letters
original_names Total eve charge Total eve minutes Total intl calls
0                           NaN               NaN              NaN
1                           NaN               NaN              NaN
2                           NaN               NaN              NaN
3                           NaN               NaN              NaN
4                           NaN               NaN              NaN
..                          ...               ...              ...
662                         NaN               NaN              NaN
663                         NaN               NaN              NaN
664                         NaN               NaN              NaN
665                         NaN               NaN              NaN
666                         NaN               NaN              NaN

numbers                                                                \
letters
original_names Total intl charge Total intl minutes Total night calls
0                            NaN                NaN               NaN
1                            NaN                NaN               NaN
2                            NaN                NaN               NaN
3                            NaN                NaN               NaN
4                            NaN                NaN               NaN
..                           ...                ...               ...
662                          NaN                NaN               NaN
663                          NaN                NaN               NaN
664                          NaN                NaN               NaN
665                          NaN                NaN               NaN
666                          NaN                NaN               NaN

numbers
letters
original_names Total night charge Total night minutes Voice mail plan
0                             NaN                 NaN             NaN
1                             NaN                 NaN             NaN
2                             NaN                 NaN             NaN
3                             NaN                 NaN             NaN
4                             NaN                 NaN             NaN
..                            ...                 ...             ...
662                           NaN                 NaN             NaN
663                           NaN                 NaN             NaN
664                           NaN                 NaN             NaN
665                           NaN                 NaN             NaN
666                           NaN                 NaN             NaN

[667 rows x 400 columns]

In [63]:
# Unstack the row 'One_k' and 'letters'...
df_stacked.unstack(0)

ValueError: Index contains duplicate entries, cannot reshape

In [32]:
# Unstack the row 'letters' - Don't save the changes
df_stacked.unstack('letters')

numbers        10                                               ...   29       \
letters         A    B    C    D    E    F    G    H    I    J  ...    K    L
One_k Three_k                                                   ...
1000  3000     LA  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN
1001  3001     IN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN
1002  3002     NY  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN
1003  3003     SC  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN
1004  3004     HI  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN
...            ..  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
1662  3662     WI  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN
1663  3663     AL  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN
1664  3664     VT  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN
1665  3665     WV  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN
1666  3666     CT  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN

numbers
letters          M    N    O    P    Q    R    S      T
One_k Three_k
1000  3000     NaN  NaN  NaN  NaN  NaN  NaN  NaN  False
1001  3001     NaN  NaN  NaN  NaN  NaN  NaN  NaN   True
1002  3002     NaN  NaN  NaN  NaN  NaN  NaN  NaN   True
1003  3003     NaN  NaN  NaN  NaN  NaN  NaN  NaN  False
1004  3004     NaN  NaN  NaN  NaN  NaN  NaN  NaN  False
...            ...  ...  ...  ...  ...  ...  ...    ...
1662  3662     NaN  NaN  NaN  NaN  NaN  NaN  NaN  False
1663  3663     NaN  NaN  NaN  NaN  NaN  NaN  NaN  False
1664  3664     NaN  NaN  NaN  NaN  NaN  NaN  NaN  False
1665  3665     NaN  NaN  NaN  NaN  NaN  NaN  NaN  False
1666  3666     NaN  NaN  NaN  NaN  NaN  NaN  NaN  False

[667 rows x 400 columns]

In [18]:
# Original DF
churn.head()

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,LA,117,408,No,No,0,184.5,97,31.37,351.6,80,29.89,215.8,90,9.71,8.7,4,2.35,1,False
1,IN,65,415,No,No,0,129.1,137,21.95,228.5,83,19.42,208.8,111,9.40,12.7,6,3.43,4,True
2,NY,161,415,No,No,0,332.9,67,56.59,317.8,97,27.01,160.6,128,7.23,5.4,9,1.46,4,True
3,SC,111,415,No,No,0,110.4,103,18.77,137.3,102,11.67,189.6,105,8.53,7.7,6,2.08,2,False
4,HI,49,510,No,No,0,119.3,117,20.28,215.1,109,18.28,178.7,90,8.04,11.1,1,3.00,1,False